#!/usr/bin/env bash
cd "$(dirname "${BASH_SOURCE[0]}")"
set -e

PAGE_HTML_DECL='static const char PAGE_HTML'

trim_and_remove_newlines() {
    sed 's/^[ \t]*//;s/[ \t]*$//;s/"/\\"/g' | tr -d '\r\n'
}

print_new_c_file_with_html() {
    sed -n "/$PAGE_HTML_DECL/!p;//q" "$1"
    echo "$PAGE_HTML_DECL[] = \"$2\";"
    sed "1,/$PAGE_HTML_DECL/d" "$1"
}

replace_token_with_file() {
    while read line; do
        if [[ "$line" = *"$1"* ]]; then
            cat "$2"
        else
            echo "$line"
        fi
    done
    echo "$line"
}

main() {
    local page_bundle="$(cat webscope.html \
        | replace_token_with_file __CSS__ 'webscope.css' \
        | replace_token_with_file __JS__ 'webscope.js' \
        | trim_and_remove_newlines)"

    print_new_c_file_with_html 'webscope.c' "$page_bundle" > tmp.c
    mv tmp.c webscope.c
}

main
